version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: fhir_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mirth-db:
    image: postgres:16
    container_name: mirth-db
    environment:
      POSTGRES_DB: mirth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - mirth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mirth:
    image: nextgenhealthcare/connect:latest
    container_name: mirth-connect
    ports:
      - "8080:8080"
      - "8443:8443"
      - "6661:6661"
    environment:
      # Tell Mirth to use Postgres
      DATABASE: postgres
      # Use the service name "db" as the host
      DATABASE_URL: jdbc:postgresql://mirth-db:5432/mirth_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      mirth-db:
        condition: service_healthy
    volumes:
      - mirth_data:/opt/connect/appdata

volumes:
  postgres_data:
  mirth_data:
  mirth_db_data: