spring.application.name=fhir
server.port=8081

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/fhir_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

## Run schema.sql on startup
#spring.sql.init.mode=always


