spring.application.name=fhir

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/fhir_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop